/**
 * ABI Generation Script
 * 
 * Extracts contract ABIs from compiled contracts in the build directory
 * and saves them to the contracts folder for use in the React app.
 * 
 * This script reads the compiled JSON files from the contracts/build/ directory
 * (generated by Truffle compiler) and extracts just the ABI, then saves them
 * to src/contracts/ for import in React components.
 * 
 * Usage: node scripts/generateABIs.js
 * Or: npm run generate-abis
 */

const fs = require('fs');
const path = require('path');

// Define contract files and their destinations
const contracts = [
  { name: 'DynamicNFT', buildPath: '../contracts/build/contracts/DynamicNFT.json' },
  { name: 'ReputationNFT', buildPath: '../contracts/build/contracts/ReputationNFT.json' },
  { name: 'FastTransfer', buildPath: '../contracts/build/contracts/FastTransfer.json' },
  { name: 'UtilityTicketNFT', buildPath: '../contracts/build/contracts/UtilityTicketNFT.json' }
];

const outputDir = path.join(__dirname, '../src/contracts');

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
  console.log(`📁 Created directory: ${outputDir}`);
}

console.log('📦 Generating Contract ABIs...\n');

let successCount = 0;
let errorCount = 0;

contracts.forEach(contract => {
  const buildPath = path.join(__dirname, contract.buildPath);
  const outputPath = path.join(outputDir, `${contract.name}.json`);

  try {
    // Check if build file exists
    if (!fs.existsSync(buildPath)) {
      console.warn(`⚠️  Build file not found: ${buildPath}`);
      console.log(`   Run 'truffle compile' first to generate contract build files.\n`);
      errorCount++;
      return;
    }

    // Read the compiled contract
    const compiledContract = JSON.parse(fs.readFileSync(buildPath, 'utf8'));

    // Extract ABI
    const abi = compiledContract.abi;
    if (!abi) {
      console.error(`❌ No ABI found in: ${contract.name}`);
      errorCount++;
      return;
    }

    // Create output with ABI and useful metadata
    const output = {
      contractName: contract.name,
      abi: abi,
      networks: compiledContract.networks || {},
      deployedBytecode: compiledContract.deployedBytecode || null,
      schemaVersion: compiledContract.schemaVersion,
      updatedAt: new Date().toISOString()
    };

    // Write ABI to file
    fs.writeFileSync(outputPath, JSON.stringify(output, null, 2));
    console.log(`✅ ${contract.name}: ${outputPath}`);
    successCount++;

  } catch (error) {
    console.error(`❌ Error processing ${contract.name}:`, error.message);
    errorCount++;
  }
});

console.log(`\n=== ABI Generation Complete ===`);
console.log(`✅ Successful: ${successCount}`);
if (errorCount > 0) {
  console.log(`❌ Errors: ${errorCount}`);
  console.log(`\nTo generate contract build files, run: truffle compile`);
  process.exit(1);
} else {
  console.log(`\n📝 ABIs are ready to use in React components:`);
  console.log(`   import DynamicNFT from '../contracts/DynamicNFT.json';`);
  console.log(`   const contractABI = DynamicNFT.abi;`);
}
